# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🚀 Release

on:
  release: {types: [published]}
  workflow_dispatch: {}

jobs:
  build-docker-image:
    name: Build the docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - {uses: gacts/github-slug@v1, id: slug}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.actor }}/3proxy:latest
            ghcr.io/${{ github.actor }}/3proxy:${{ steps.slug.outputs.version-semantic }}
            ghcr.io/${{ github.actor }}/3proxy:${{ steps.slug.outputs.version-major }}.${{ steps.slug.outputs.version-minor }}
            ghcr.io/${{ github.actor }}/3proxy:${{ steps.slug.outputs.version-major }}
            docker.io/tarampampam/3proxy:latest
            docker.io/tarampampam/3proxy:${{ steps.slug.outputs.version-semantic }}
            docker.io/tarampampam/3proxy:${{ steps.slug.outputs.version-major }}.${{ steps.slug.outputs.version-minor }}
            docker.io/tarampampam/3proxy:${{ steps.slug.outputs.version-major }}
